apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tayari-frontend
spec:
  minAvailable: 0
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tayari-go-gateway
spec:
  minAvailable: 0
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tayari-python-api
spec:
  minAvailable: 0
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tayari-frontend
spec:
  minReplicas: 1
  maxReplicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tayari-go-gateway
spec:
  minReplicas: 1
  maxReplicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tayari-python-api
spec:
  minReplicas: 1
  maxReplicas: 1
