apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: tayari-development
patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: tayari
  - path: runtime-config-patch.yaml
    target:
      kind: ConfigMap
      name: tayari-runtime-config
  - path: replica-patch.yaml
  - path: ingress-patch.yaml
  - path: availability-patch.yaml
