package models

import (
	"time"
)

// AutopilotRun tracks a background Auto-Pilot job search run.
type AutopilotRun struct {
	ID                  int       `json:"id"`
	RunID               string    `json:"run_id"`
	UserID              string    `json:"user_id"`
	Config              JSONMap   `json:"config,omitempty"`
	Status              string    `json:"status"` // pending, running, completed, failed
	Progress            int       `json:"progress"`
	CurrentStep         string    `json:"current_step,omitempty"`
	Logs                LogEntrySlice `json:"logs,omitempty"`
	ApplicationsCreated int       `json:"applications_created"`
	Error               string    `json:"error,omitempty"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

// Application tracks an individual job application generated by Auto-Pilot or manually created.
type Application struct {
	ID               int       `json:"id"`
	ApplicationID    string    `json:"application_id"`
	UserID           string    `json:"user_id"`
	RunID            string    `json:"run_id,omitempty"`
	Job              JSONMap   `json:"job,omitempty"`
	TailoredResumeText string  `json:"tailored_resume_text,omitempty"`
	CoverLetter      string    `json:"cover_letter,omitempty"`
	Changes          JSONMap   `json:"changes,omitempty"`
	KeywordsAdded    StringSlice `json:"keywords_added,omitempty"`
	ATSScoreBefore   int       `json:"ats_score_before"`
	ATSScoreAfter    int       `json:"ats_score_after"`
	IsDreamCompany   bool      `json:"is_dream_company"`
	Status           string    `json:"status"` // applied, phone_screen, interview, offer, rejected, saved
	SubmissionMode   string    `json:"submission_mode,omitempty"`
	ApplyURL         string    `json:"apply_url,omitempty"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// AutopilotSchedule represents a recurring Auto-Pilot schedule.
type AutopilotSchedule struct {
	ID          int       `json:"id"`
	ScheduleID  string    `json:"schedule_id"`
	UserID      string    `json:"user_id"`
	Frequency   string    `json:"frequency"` // daily, weekly, biweekly
	Config      JSONMap   `json:"config,omitempty"`
	Active      bool      `json:"active"`
	NextRunAt   *time.Time `json:"next_run_at,omitempty"`
	LastRunAt   *time.Time `json:"last_run_at,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
}
