apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tayari-public
spec:
  tls:
    - hosts:
        - staging.job-tayari.example.invalid
      secretName: stg-tayari-public-tls
  rules:
    - host: staging.job-tayari.example.invalid
