apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tayari-frontend
  labels:
    app.kubernetes.io/part-of: job-tayari
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tayari-go-gateway
  labels:
    app.kubernetes.io/part-of: job-tayari
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tayari-python-api
  labels:
    app.kubernetes.io/part-of: job-tayari
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-ai
