apiVersion: v1
kind: Namespace
metadata:
  name: tayari
  labels:
    app.kubernetes.io/part-of: job-tayari
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
