apiVersion: v1
kind: ServiceAccount
metadata:
  name: tayari-frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: job-tayari
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tayari-gateway
  labels:
    app.kubernetes.io/name: go-gateway
    app.kubernetes.io/part-of: job-tayari
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tayari-python-api
  labels:
    app.kubernetes.io/name: python-ai
    app.kubernetes.io/part-of: job-tayari
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tayari-worker
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: job-tayari
automountServiceAccountToken: false
