(() => {
  const SESSION_KEY = 'tayari_extension_session_v1';
  const PROFILE_CACHE_KEY = 'tayari_profile_cache';
  async function read() { const result = await chrome.storage.local.get(SESSION_KEY); return result[SESSION_KEY] || null; }
  async function write(session) { if (!session?.access_token) throw new Error('Invalid extension session.'); await chrome.storage.local.set({ [SESSION_KEY]: { access_token: session.access_token, refresh_token: session.refresh_token || null, expires_at: session.expires_at || Math.floor(Date.now() / 1000) + (session.expires_in || 3600), user: session.user || null, client: 'chrome-extension' } }); await chrome.storage.local.remove([PROFILE_CACHE_KEY, `${PROFILE_CACHE_KEY}_timestamp`]); return read(); }
  async function clear() { await chrome.storage.local.remove([SESSION_KEY, PROFILE_CACHE_KEY, `${PROFILE_CACHE_KEY}_timestamp`]); }
  function isExpired(session, leewaySeconds = 45) { return !session?.access_token || Number(session.expires_at || 0) <= Math.floor(Date.now() / 1000) + leewaySeconds; }
  async function refresh(supabaseUrl, publishableKey) { const session = await read(); if (!session?.refresh_token) return null; const response = await fetch(`${String(supabaseUrl).replace(/\/$/, '')}/auth/v1/token?grant_type=refresh_token`, { method: 'POST', headers: { apikey: publishableKey, 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: session.refresh_token }) }); if (!response.ok) { await clear(); return null; } return write(await response.json()); }
  async function getValid(config) { let session = await read(); if (session && !isExpired(session)) return session; if (!config?.supabaseUrl || !config?.supabaseKey) return session; return refresh(config.supabaseUrl, config.supabaseKey); }
  async function fetchJson(config, path, init = {}) { let session = await getValid(config); if (!session?.access_token) throw new Error('Sign in to Job Tayari first.'); const headers = new Headers(init.headers || {}); headers.set('Authorization', `Bearer ${session.access_token}`); headers.set('Content-Type', 'application/json'); let response = await fetch(`${String(config.apiUrl).replace(/\/$/, '')}/${String(path).replace(/^\//, '')}`, { ...init, headers }); if (response.status === 401 && session.refresh_token && config.supabaseUrl && config.supabaseKey) { session = await refresh(config.supabaseUrl, config.supabaseKey); if (!session?.access_token) throw new Error('Your Job Tayari session expired.'); headers.set('Authorization', `Bearer ${session.access_token}`); response = await fetch(`${String(config.apiUrl).replace(/\/$/, '')}/${String(path).replace(/^\//, '')}`, { ...init, headers }); } return response; }
  globalThis.TayariSession = { SESSION_KEY, read, write, clear, refresh, getValid, fetchJson, isExpired };
})();
