// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

function requireMcpWriteTool(ctx, toolName) {
  const denied = (reason) => {
    const detail = { code: "disabled_by_launch_scope", capability: "mcp.write_tools", tool: toolName, reason };
    return { content: [{ type: "text", text: JSON.stringify(detail) }], isError: true, structuredContent: detail };
  };
  if (!ctx.isAuthenticated()) return denied("authenticated MCP context required");
  const raw = globalThis.Deno?.env?.get?.("CAPABILITY_MCP_WRITE_TOOLS") ?? process.env.CAPABILITY_MCP_WRITE_TOOLS;
  if (!["1", "true", "yes", "on"].includes(String(raw ?? "").trim().toLowerCase())) return denied("MCP write tools are disabled by launch scope");
  return null;
}

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get the signed-in user's Tayari profile (name, headline, preferences).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/search-jobs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_jobs_default = defineTool2({
  name: "search_saved_jobs",
  title: "Search saved jobs",
  description: "Search the signed-in user's saved jobs by title, company, or keyword.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Text to match against title/company/description"),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb2(ctx);
    const { data, error } = await client.from("saved_jobs").select("id,title,company,location,url,status,created_at").eq("user_id", ctx.getUserId()).or(`title.ilike.%${query}%,company.ilike.%${query}%`).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_applications_default = defineTool3({
  name: "list_applications",
  title: "List applications",
  description: "List the signed-in user's job applications on the Interview Board, optionally filtered by stage.",
  inputSchema: {
    stage: z2.enum(["saved", "applied", "phone_screen", "interview", "offer", "rejected"]).optional().describe("Filter by pipeline stage"),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("saved_jobs").select("id,title,company,location,url,status,created_at,updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (stage) q = q.eq("status", stage);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-job.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_job_default = defineTool4({
  name: "save_job",
  title: "Save a job",
  description: "Save a job to the signed-in user's saved list / Interview Board.",
  inputSchema: {
    title: z3.string().trim().min(1),
    company: z3.string().trim().min(1),
    location: z3.string().optional(),
    url: z3.string().url().optional(),
    description: z3.string().optional(),
    status: z3.enum(["saved", "applied", "phone_screen", "interview", "offer", "rejected"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, company, location, url, description, status }, ctx) => {
    const gate = requireMcpWriteTool(ctx, "save_job");
    if (gate) return gate;
    const { data, error } = await sb4(ctx).from("saved_jobs").insert({
      user_id: ctx.getUserId(),
      title,
      company,
      location: location ?? null,
      url: url ?? null,
      description: description ?? null,
      status: status ?? "saved"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved ${title} at ${company}` }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/optimize-resume.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_client.ts
function runtimeGoApiUrl() {
  const runtime = globalThis.Deno?.env?.get?.("TAYARI_GO_API_URL");
  return runtime ?? "";
}
var API = () => {
  const configured = String(runtimeGoApiUrl()).trim();
  if (configured) return configured;
  throw new Error("MCP Go API URL is not configured");
};
var REQUEST_TIMEOUT_MS = 6e4;
var ApiError = class extends Error {
  data;
};
async function callApi(ctx, path, options = {}) {
  const timeoutMs = options.timeoutMs ?? REQUEST_TIMEOUT_MS;
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  let resp;
  try {
    resp = await fetch(`${API()}${path}`, {
      method: options.method ?? "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${ctx.getToken()}` },
      body: options.body === void 0 ? void 0 : JSON.stringify(options.body),
      signal: controller.signal
    });
  } catch (err) {
    const isTimeout = err instanceof Error && err.name === "AbortError";
    throw new Error(
      isTimeout ? `Request timed out after ${timeoutMs}ms` : `Network error: ${err instanceof Error ? err.message : String(err)}`
    );
  } finally {
    clearTimeout(timeoutId);
  }
  let data;
  try {
    data = await resp.json();
  } catch (err) {
    throw new Error(`Invalid response from server: ${err instanceof Error ? err.message : String(err)}`);
  }
  if (!resp.ok) {
    const msg = typeof data === "object" && data !== null && "error" in data && typeof data.error === "string" ? data.error || "Failed" : "Failed";
    const err = new ApiError(msg);
    err.data = data;
    throw err;
  }
  return data;
}
function toolError(text) {
  return { content: [{ type: "text", text }], isError: true };
}

// src/lib/mcp/tools/optimize-resume.ts
var optimize_resume_default = defineTool5({
  name: "optimize_resume",
  title: "Optimize resume",
  description: "Tailor the user's resume to a specific job description using AI. Returns the optimized resume text and a list of changes made.",
  inputSchema: {
    resume_id: z4.number().int().describe("ID of the resume to optimize"),
    job_description: z4.string().min(20).describe("The target job description text")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ resume_id, job_description }, ctx) => {
    const gate = requireMcpWriteTool(ctx, "optimize_resume");
    if (gate) return gate;
    try {
      const data = await callApi(ctx, `/api/v1/resumes/${resume_id}/optimize`, {
        body: { job_description },
        timeoutMs: REQUEST_TIMEOUT_MS
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/get-ats-score.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^4.4.3";
var get_ats_score_default = defineTool6({
  name: "get_ats_score",
  title: "Get ATS score",
  description: "Score a resume against a job description. Returns overall_score, match_score, missing_skills, and recommendations.",
  inputSchema: {
    resume_text: z5.string().min(10).describe("Resume text to analyze"),
    job_description: z5.string().min(20).describe("Job description to score against")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ resume_text, job_description }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    try {
      const data = await callApi(ctx, "/api/v1/analyze", {
        body: { resume_text, job_description }
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/generate-cover-letter.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^4.4.3";
var generate_cover_letter_default = defineTool7({
  name: "generate_cover_letter",
  title: "Generate cover letter",
  description: "Generate a tailored cover letter for a job application based on the user's resume.",
  inputSchema: {
    resume_id: z6.number().int().describe("Resume ID to base the cover letter on"),
    job_description: z6.string().min(20).describe("Target job description"),
    company_name: z6.string().optional().describe("Company name for personalization"),
    tone: z6.enum(["professional", "friendly", "confident"]).optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ resume_id, job_description, company_name, tone }, ctx) => {
    const gate = requireMcpWriteTool(ctx, "generate_cover_letter");
    if (gate) return gate;
    try {
      const data = await callApi(ctx, "/api/v1/cover-letter/generate", {
        body: { resume_id, job_description, company_name, tone }
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/get-pipeline.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z7 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_pipeline_default = defineTool8({
  name: "get_pipeline",
  title: "Get application pipeline",
  description: "List all job applications in the user's pipeline, optionally filtered by stage.",
  inputSchema: {
    stage: z7.enum(["saved", "applied", "screening", "interview", "offer", "rejected", "accepted"]).optional(),
    limit: z7.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!process.env.SUPABASE_URL || !process.env.SUPABASE_PUBLISHABLE_KEY) {
      return { content: [{ type: "text", text: "Server misconfigured: SUPABASE_URL/SUPABASE_PUBLISHABLE_KEY not set" }], isError: true };
    }
    let q = sb5(ctx).from("applications").select("application_id,title,company,stage,status,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { applications: data ?? [] } };
  }
});

// src/lib/mcp/tools/add-to-pipeline.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z8 } from "npm:zod@^4.4.3";
var add_to_pipeline_default = defineTool9({
  name: "add_to_pipeline",
  title: "Add job to pipeline",
  description: "Add a job to the user's application pipeline (kanban board).",
  inputSchema: {
    title: z8.string().describe("Job title"),
    company: z8.string().describe("Company name"),
    url: z8.string().url().optional().describe("Job listing URL"),
    location: z8.string().optional(),
    description: z8.string().optional().describe("Job description text"),
    stage: z8.enum(["saved", "applied", "screening"]).optional().default("saved")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, company, url, location, description, stage }, ctx) => {
    const gate = requireMcpWriteTool(ctx, "add_to_pipeline");
    if (gate) return gate;
    try {
      const data = await callApi(ctx, "/api/v1/extension/capture", {
        body: { title, company, url, location, description, stage, add_to_board: true }
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/get-interview-questions.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z9 } from "npm:zod@^4.4.3";
var get_interview_questions_default = defineTool10({
  name: "get_interview_questions",
  title: "Get interview questions",
  description: "Generate likely interview questions for a role and company, with guidance on how to answer each one.",
  inputSchema: {
    resume_id: z9.number().int().describe("Resume ID to tailor questions to"),
    job_description: z9.string().min(20).describe("Target job description"),
    company: z9.string().optional().describe("Company name for company-specific questions")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ resume_id, job_description, company }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    try {
      const data = await callApi(ctx, "/api/v1/interview/prep", {
        body: { resume_id, job_description, company }
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/get-skill-gaps.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z10 } from "npm:zod@^4.4.3";
var get_skill_gaps_default = defineTool11({
  name: "get_skill_gaps",
  title: "Get skill gaps",
  description: "Analyze skill gaps between the user's resume and a target role or job description. Returns matched skills, missing skills, and a learning path.",
  inputSchema: {
    resume_id: z10.number().int().optional().describe("Resume ID (uses latest if omitted)"),
    job_description_text: z10.string().optional().describe("Job description text"),
    target_role: z10.string().optional().describe("Target role e.g. 'Staff Engineer'")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    if (!args.job_description_text && !args.target_role) {
      return toolError("At least one of job_description_text or target_role is required");
    }
    try {
      const data = await callApi(ctx, "/api/v1/career-intelligence/skills-gap", {
        body: {
          resume_id: args.resume_id,
          job_description_text: args.job_description_text,
          target_role: args.target_role
        }
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/get-market-salary.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z11 } from "npm:zod@^4.4.3";
var get_market_salary_default = defineTool12({
  name: "get_market_salary",
  title: "Get market salary",
  description: "Get salary benchmarks for a role in a given location. Returns p25, median, p75, and total compensation breakdown.",
  inputSchema: {
    target_role: z11.string().describe("Job title/role e.g. 'Senior Software Engineer'"),
    location: z11.string().optional().default("US").describe("Location e.g. 'San Francisco, CA' or country code")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ target_role, location }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    try {
      const data = await callApi(ctx, "/api/v1/career-intelligence/salary-benchmark", {
        body: { target_role, location }
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/check-company.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z12 } from "npm:zod@^4.4.3";
var check_company_default = defineTool13({
  name: "check_company",
  title: "Check company",
  description: "Look up company information including culture signals, review patterns, ATS used, and known hiring contacts.",
  inputSchema: {
    company_name: z12.string().describe("Company name to look up"),
    job_url: z12.string().url().optional().describe("Optional job posting URL for more context")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ company_name, job_url }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    try {
      const data = await callApi(ctx, "/api/v1/agent-reach/doctor", {
        body: { company: company_name, url: job_url }
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/report-outcome.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z13 } from "npm:zod@^4.4.3";
var report_outcome_default = defineTool14({
  name: "report_outcome",
  title: "Report application outcome",
  description: "Record the real-world outcome of a job application (recruiter replied, got interview, received offer, etc.). Used to improve autopilot accuracy.",
  inputSchema: {
    application_id: z13.string().uuid().describe("Application UUID"),
    recruiter_reply: z13.boolean().optional(),
    phone_screen: z13.boolean().optional(),
    technical_interview: z13.boolean().optional(),
    final_interview: z13.boolean().optional(),
    offer_received: z13.boolean().optional(),
    offer_accepted: z13.boolean().optional(),
    salary_offered: z13.number().optional().describe("Offered salary in USD"),
    notes: z13.string().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ application_id, ...rest }, ctx) => {
    const gate = requireMcpWriteTool(ctx, "report_outcome");
    if (gate) return gate;
    if (Object.keys(rest).length === 0) {
      return toolError("At least one outcome field is required");
    }
    try {
      const data = await callApi(ctx, `/api/v1/applications/${application_id}/outcome`, {
        body: rest
      });
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { data } };
    } catch (err) {
      return toolError(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/index.ts
function runtimeSupabaseUrl() {
  const runtime = globalThis.Deno?.env?.get?.("SUPABASE_URL");
  return runtime ?? "";
}
function projectRefFromSupabaseUrl() {
  const raw = String(runtimeSupabaseUrl());
  if (!raw) return "";
  let parsed;
  try {
    parsed = new URL(raw);
  } catch {
    return "";
  }
  if (parsed.protocol !== "https:") return "";
  const host = parsed.hostname.toLowerCase();
  const match = /^([a-z0-9]{20})\.supabase\.co$/.exec(host);
  if (!match) return "";
  return match[1];
}
var projectRef = projectRefFromSupabaseUrl() || "";
if (!projectRef) {
  throw new Error("MCP auth issuer is not configured with a valid hosted Supabase project");
}
var mcp_default = defineMcp({
  name: "tayari-mcp",
  title: "Tayari",
  version: "0.2.0",
  instructions: "Tayari is an AI job-prep and application-automation platform. Tools cover the full funnel: profile, saved jobs, pipeline management, resume optimization, ATS scoring, cover letter generation, interview prep, skill gap analysis, salary benchmarks, company intelligence, and outcome reporting.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    // Read profile & pipeline
    get_profile_default,
    get_pipeline_default,
    list_applications_default,
    // Job management
    search_jobs_default,
    save_job_default,
    add_to_pipeline_default,
    // AI-powered tools
    optimize_resume_default,
    get_ats_score_default,
    generate_cover_letter_default,
    get_interview_questions_default,
    get_skill_gaps_default,
    // Market intelligence
    get_market_salary_default,
    check_company_default,
    // Outcome loop (M2)
    report_outcome_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
