// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get the signed-in user's Tayari profile (name, headline, preferences).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/search-jobs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_jobs_default = defineTool2({
  name: "search_saved_jobs",
  title: "Search saved jobs",
  description: "Search the signed-in user's saved jobs by title, company, or keyword.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Text to match against title/company/description"),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb2(ctx);
    const { data, error } = await client.from("saved_jobs").select("id,title,company,location,url,status,created_at").eq("user_id", ctx.getUserId()).or(`title.ilike.%${query}%,company.ilike.%${query}%`).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_applications_default = defineTool3({
  name: "list_applications",
  title: "List applications",
  description: "List the signed-in user's job applications on the Interview Board, optionally filtered by stage.",
  inputSchema: {
    stage: z2.enum(["saved", "applied", "phone_screen", "interview", "offer", "rejected"]).optional().describe("Filter by pipeline stage"),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("saved_jobs").select("id,title,company,location,url,status,created_at,updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (stage) q = q.eq("status", stage);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-job.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_job_default = defineTool4({
  name: "save_job",
  title: "Save a job",
  description: "Save a job to the signed-in user's saved list / Interview Board.",
  inputSchema: {
    title: z3.string().trim().min(1),
    company: z3.string().trim().min(1),
    location: z3.string().optional(),
    url: z3.string().url().optional(),
    description: z3.string().optional(),
    status: z3.enum(["saved", "applied", "phone_screen", "interview", "offer", "rejected"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, company, location, url, description, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("saved_jobs").insert({
      user_id: ctx.getUserId(),
      title,
      company,
      location: location ?? null,
      url: url ?? null,
      description: description ?? null,
      status: status ?? "saved"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved ${title} at ${company}` }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = Deno.env.get("SUPABASE_PROJECT_REF") || "";
if (!projectRef) {
  throw new Error("SUPABASE_PROJECT_REF is not set — configure it in your Supabase Edge Function secrets or environment variables.");
}
var mcp_default = defineMcp({
  name: "tayari-mcp",
  title: "Tayari",
  version: "0.1.0",
  instructions: "Tayari is an AI job-prep platform. Use these tools to read the signed-in user's profile, search their saved jobs, list Interview Board applications by stage, and save new jobs to their board.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, search_jobs_default, list_applications_default, save_job_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
