-- One-time web-session to browser-extension handoff codes.
-- The code is stored only as a SHA-256 hash and is consumed exactly once.
CREATE TABLE IF NOT EXISTS public.extension_session_handoff_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS extension_session_handoff_tokens_active_idx
  ON public.extension_session_handoff_tokens (token_hash, expires_at)
  WHERE used_at IS NULL;

ALTER TABLE public.extension_session_handoff_tokens ENABLE ROW LEVEL SECURITY;

-- The Go gateway accesses this table with the server database role. No direct
-- browser policy is granted because handoff codes must never be enumerable.
REVOKE ALL ON TABLE public.extension_session_handoff_tokens FROM anon, authenticated;
GRANT ALL ON TABLE public.extension_session_handoff_tokens TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.extension_session_handoff_tokens_id_seq TO service_role;
